version: '3.8'

services:
  minecraft:
    build:
      context: .
      args:
        SERVER_JAR_URL: https://piston-data.mojang.com/v1/objects/5b868151bd02b41319f54c8d4061b8cae84e665c/server.jar
    ports:
      - "25565:25565"
    volumes:
      - ./data:/minecraft
    restart: unless-stopped
